name: Deploy_main
env:
  SSH_USER: 'root'
  SSH_HOST: '150.241.78.240'
  SSH_PORT: '22'
  REPO_NAME: ${{ github.event.repository.name }}



on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Git clone
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ env.SSH_PORT }} -H ${{ env.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup repo folder
        run: |
          ssh -p ${{ env.SSH_PORT }} ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "mkdir -p /opt/repos/${{ env.REPO_NAME }}"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Check
        run: |
          ls -la

      - name: Copy dist dir to dev host
        run: |
          scp -v -P ${{ env.SSH_PORT }} -i ~/.ssh/id_rsa -r dist/ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:/opt/repos/${{ env.REPO_NAME }}
